[package]
name = "better-fetch-mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
html2md = "0.2.15"
reqwest = { version = "0.12.23", features = ["rustls-tls"] }
rmcp = "0.8.0"
schemars = { version = "1.0.4", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
url = "2.5.7"

[dev-dependencies]
insta = "1.43.2"
tempfile = "3.23.0"
walkdir = "2.5.0"
